"""3D-pipeline end-to-end gate (pipeline:=3d, HUMBLE ONLY): synthetic scene →
crop box → cloud_object_detector → autoware_multi_object_tracker, asserting
on /perception/tracked_objects:

  * the floor grid does not become an object (z-band works),
  * the pillar is tracked as a POLYGON with a plausible footprint and height,
  * its velocity estimate converges to the scene's commanded +y speed,
  * the track id stays stable through the crossing.

The scene is generated by scene_3d_source.py (no fixture bag, no MuJoCo);
its SPEED constant is the ground truth. Skips on Foxy, where the autoware
stack is not built (the 3D pipeline is Humble-only by decision, 2026-08-26).

Standalone:
  launch_test src/g1_perception/g1_perception_bringup/test/test_tracking_3d.launch_test.py
"""
import os as _os, sys as _sys  # noqa: E402
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))  # noqa: E402
import isolate_domain  # noqa: E402
isolate_domain.isolate(isolate_domain.TRACKING_3D)  # noqa: E402

import math
import os
import sys
import threading
import time
import unittest

import launch
import launch_testing.actions
import pytest

HERE = os.path.dirname(os.path.abspath(__file__))

try:
    import autoware_perception_msgs.msg  # noqa: F401
    SKIP_REASON = None
except ImportError:
    SKIP_REASON = ('autoware_perception_msgs not built — the 3D pipeline is '
                   'Humble-only and not part of the Foxy build set')

import scene_3d_source  # noqa: E402  (constants are the ground truth)

COLLECT_S = 16.0
# scene time window where the pillar is still moving (it stops at
# (Y_STOP - Y_START) / SPEED = 8 s) and the CV filter has had time to settle.
WINDOW_S = (4.0, 7.5)
SPEED_TOL = 0.2          # [m/s] on both twist magnitude and displacement rate
HEIGHT_RANGE = (0.7, 1.4)  # true visible height ~1.1 m (z band cuts < 0.10)
MIN_ID_FRACTION = 0.8


@pytest.mark.launch_test
def generate_test_description():
    if SKIP_REASON:
        return launch.LaunchDescription([launch_testing.actions.ReadyToTest()])
    from ament_index_python.packages import get_package_share_directory
    from launch.launch_description_sources import PythonLaunchDescriptionSource
    launch_dir = os.path.join(
        get_package_share_directory('g1_perception_bringup'), 'launch')
    return launch.LaunchDescription([
        launch.actions.IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(launch_dir, 'perception_3d.launch.py')),
            launch_arguments=[('use_sim_time', 'false')]),
        launch.actions.ExecuteProcess(
            cmd=[sys.executable, os.path.join(HERE, 'scene_3d_source.py')],
            output='screen'),
        launch_testing.actions.ReadyToTest(),
    ])


class TestTracking3d(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if SKIP_REASON:
            return
        import rclpy
        from rclpy.qos import (QoSProfile, QoSReliabilityPolicy,
                               QoSHistoryPolicy)
        from autoware_perception_msgs.msg import TrackedObjects

        rclpy.init()
        cls._node = rclpy.create_node('tracking_3d_probe')
        cls._samples = []          # (recv_time, TrackedObjects)
        cls._lock = threading.Lock()
        # BEST_EFFORT matches either publisher reliability.
        qos = QoSProfile(depth=10,
                         reliability=QoSReliabilityPolicy.BEST_EFFORT,
                         history=QoSHistoryPolicy.KEEP_LAST)
        cls._sub = cls._node.create_subscription(
            TrackedObjects, '/perception/tracked_objects',
            lambda m: cls._on_msg(m), qos)
        from perception_3d_msgs.msg import ConvexObjects
        cls._convex = []
        cls._convex_sub = cls._node.create_subscription(
            ConvexObjects, '/perception/tracked_convex',
            lambda m: cls._on_convex(m), qos)
        cls._t0 = time.monotonic()
        cls._spin = threading.Thread(
            target=rclpy.spin, args=(cls._node,), daemon=True)
        cls._spin.start()
        time.sleep(COLLECT_S)

    @classmethod
    def _on_msg(cls, msg):
        with cls._lock:
            cls._samples.append((time.monotonic() - cls._t0, msg))

    @classmethod
    def _on_convex(cls, msg):
        with cls._lock:
            cls._convex.append((time.monotonic() - cls._t0, msg))

    @classmethod
    def tearDownClass(cls):
        if SKIP_REASON:
            return
        import rclpy
        rclpy.try_shutdown()

    def _window(self):
        """Samples in the assertion window that contain exactly the pillar.

        The window starts well after both processes are up, so scene time and
        probe time agree to within startup jitter that WINDOW_S absorbs.
        """
        with self._lock:
            return [(t, m) for (t, m) in self._samples
                    if WINDOW_S[0] <= t <= WINDOW_S[1] and m.objects]

    def test_convex_only_invariant(self):
        """Every published shape, over the WHOLE run, is a convex POLYGON.

        The pipeline's contract is convex-geometry-only — no BOUNDING_BOX,
        no CYLINDER, ever (association rows for those shapes are
        create:"null"; the detector emits POLYGON by construction). This
        checks all samples, not just the assertion window, so a box sneaking
        out during track birth/death would fail here.
        """
        if SKIP_REASON:
            self.skipTest(SKIP_REASON)
        from autoware_perception_msgs.msg import Shape
        with self._lock:
            samples = list(self._samples)
        checked = 0
        for _, m in samples:
            for obj in m.objects:
                self.assertEqual(
                    obj.shape.type, Shape.POLYGON,
                    f'non-POLYGON shape type {obj.shape.type} published')
                self.assertGreaterEqual(
                    len(obj.shape.footprint.points), 3,
                    'POLYGON with a degenerate footprint published')
                checked += 1
        self.assertGreater(checked, 0, 'no objects published at all')

    def test_tracked_convex_polytopes(self):
        """/perception/tracked_convex carries one closed 3D convex polytope per
        track, bound to the track id, with the object's real z extent — not a
        single footprint extruded over the height."""
        if SKIP_REASON:
            self.skipTest(SKIP_REASON)
        with self._lock:
            convex = [(t, m) for (t, m) in self._convex
                      if WINDOW_S[0] <= t <= WINDOW_S[1] and m.objects]
        self.assertGreaterEqual(len(convex), 10, 'no tracked_convex output')
        fresh = 0
        for _, m in convex:
            for obj in m.objects:
                nv = len(obj.vertices)
                self.assertGreaterEqual(nv, 4, 'polytope needs >= 4 vertices')
                self.assertGreaterEqual(len(obj.triangles), 12,
                                        'polytope needs >= 4 faces')
                self.assertEqual(len(obj.triangles) % 3, 0)
                self.assertTrue(all(i < nv for i in obj.triangles),
                                'triangle index out of range')
                self.assertTrue(any(obj.object_id.uuid), 'unbound hull')
                zs = [v.z for v in obj.vertices]
                self.assertAlmostEqual(max(zs) - min(zs), obj.height,
                                       delta=0.05)
                self.assertGreaterEqual(obj.height, HEIGHT_RANGE[0])
                if not obj.coasting:
                    fresh += 1
        # Through the crossing the pillar is seen every frame: hulls are
        # fresh joins, not coasted carries.
        self.assertGreater(fresh, 0.8 * sum(len(m.objects) for _, m in convex))

    def test_pipeline_tracks_the_pillar(self):
        if SKIP_REASON:
            self.skipTest(SKIP_REASON)
        window = self._window()
        self.assertGreaterEqual(
            len(window), 10,
            f'expected tracked output through {WINDOW_S}, got '
            f'{len(window)} non-empty messages '
            f'({len(self._samples)} total)')

        from autoware_perception_msgs.msg import Shape

        # The floor must not spawn objects: never more than the one pillar.
        max_objects = max(len(m.objects) for _, m in window)
        self.assertEqual(
            max_objects, 1,
            f'expected exactly the pillar, saw up to {max_objects} objects '
            '(floor leaking through the z band?)')

        ids, speeds = [], []
        for _, m in window:
            obj = m.objects[0]
            ids.append(bytes(obj.object_id.uuid))
            self.assertEqual(obj.shape.type, Shape.POLYGON)
            self.assertGreaterEqual(len(obj.shape.footprint.points), 3)
            self.assertGreaterEqual(obj.shape.dimensions.z, HEIGHT_RANGE[0])
            self.assertLessEqual(obj.shape.dimensions.z, HEIGHT_RANGE[1])
            tw = obj.kinematics.twist_with_covariance.twist.linear
            # twist is in the object frame — compare magnitudes, and use
            # world displacement below for the direction.
            speeds.append(math.hypot(tw.x, tw.y))

        speeds.sort()
        median_speed = speeds[len(speeds) // 2]
        self.assertAlmostEqual(
            median_speed, scene_3d_source.SPEED, delta=SPEED_TOL,
            msg=f'median tracked speed {median_speed:.3f} vs commanded '
                f'{scene_3d_source.SPEED}')

        # Displacement rate in world frame: +y at SPEED.
        (t_a, m_a), (t_b, m_b) = window[0], window[-1]
        p_a = m_a.objects[0].kinematics.pose_with_covariance.pose.position
        p_b = m_b.objects[0].kinematics.pose_with_covariance.pose.position
        dt = t_b - t_a
        self.assertGreater(dt, 1.0)
        vy = (p_b.y - p_a.y) / dt
        vx = (p_b.x - p_a.x) / dt
        self.assertAlmostEqual(vy, scene_3d_source.SPEED, delta=SPEED_TOL,
                               msg=f'displacement vy {vy:.3f}')
        self.assertLess(abs(vx), 0.15, msg=f'displacement vx {vx:.3f}')
        self.assertAlmostEqual(
            p_a.x, scene_3d_source.PILLAR_X, delta=0.3,
            msg=f'pillar x {p_a.x:.3f} vs {scene_3d_source.PILLAR_X}')

        # ID stability across the crossing.
        dominant = max(ids.count(u) for u in set(ids))
        self.assertGreaterEqual(
            dominant / len(ids), MIN_ID_FRACTION,
            f'dominant id covers only {dominant}/{len(ids)} samples')
